[project]
name = "pd"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "google-adk==1.5.0",
    "pydantic-ai>=1.14.0",
]
